paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos.
      tags:
        - Products
      responses:
        '200':
          description: Los productos fueron obtenidos correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor, usualmente generado por una consulta defectuosa o un fallo en la base de datos.
    post:
      summary: Crear un nuevo producto.
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
      responses:
        '200':
          description: Producto creado.
  /api/products/{pid}:
    get:
      summary: Obtiene un producto de la base de datos mediante su ID.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se desea obtener.
          schema:
            type: string
      responses:
        '200':
          description: El producto fue obtenido correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado por Mongo.
        title:
          type: string
          description: Título del producto.
        description:
          type: string
          description: Descripción del producto.
        thumbnail:
          type: string
          description: Imagen del producto.
        price:
          type: number
          description: Precio del producto.
        code:
          type: number
          description: Código del producto.
        stock:
          type: number
          description: Stock del producto.
      example:
        _id: ObjectId('6489d6e467e69d9aeb6dabd5')
        title: Small Plastic Computer
        description: In ullam assumenda assumenda et vel illo repellendus fugit.
        thumbnail: http://placeimg.com/640/480
        price: 501
        code: 84733
        stock: 32841
  requestBodies: 
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto.
        description:
          type: string
          description: Descripción del producto.
        thumbnail:
          type: string
          description: Imagen del producto.
        price:
          type: number
          description: Precio del producto.
        code:
          type: number
          description: Código del producto.
        stock:
          type: number
          description: Stock del producto.
      example:
        title: Small Plastic Computer
        description: In ullam assumenda assumenda et vel illo repellendus fugit.
        thumbnail: http://placeimg.com/640/480
        price: 501
        code: 84733
        stock: 32841